# docker-compose.yml
version: '3'
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:admin123@postgres:5432/influencers
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - .:/app/

  postgres:
    image: postgres:11
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: influencers
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
